import TreeMoves.TreeRewrite
import TreeMoves.TreeRewriteDef
import TreeMoves.TreeRewriteOrd
import TreeMoves.TreeSearch
import TreeMoves.TreeInduction
import TreeMoves.TreeNormalize
import TreeMoves.PrintTree